import ClientSessionProvider from "@/components/ClientAuthProvider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth/next";
import { Inter } from "next/font/google";
import Header from "../components/layouts/Header";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions);

	return (
		<html lang="en">
			<ClientSessionProvider session={session}>
				<body className={inter.className}>
					<Header />
					{children}
				</body>
			</ClientSessionProvider>
		</html>
	);
}
